[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = "0.8.22"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
ARBITRUM_SEPOLIA_RPC = 'https://public.stackup.sh/api/v1/node/arbitrum-sepolia'

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
