name: build and test circuits
on: [pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install node_modules
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: yarn install

      - name: install rust
        run: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh

      - name: install circom
        run: |
          git clone https://github.com/iden3/circom.git
          cd circom && cargo build --release
          cargo install --path circom

      - name: build circuits
        run: |
          yarn build:circuits:dev
        id: build-circuits

      - name: test circuits
        run: |
          yarn test:circuits
        id: test-circuits