name: build and test contracts
on: [pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: build contracts
        run: |
          yarn build:contracts
        id: build-contracts

      - name: test contracts
        run: |
          yarn test:contracts
        id: test-contracts